server:
  port: 80
  context-path: ""

logging:
  level:
    tk.mybatis: INFO

spring:
  datasource:
    url: jdbc:mysql://172.28.1.3:3306/spring_boot_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: monda43%-346ujNyu7deJ
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true






